### ISSUE TITLE
请问有Node后端的实现吗？

### ISSUE THREAD

**Issue by hezhongfeng** [APIJSON/APIJSON-Demo#14]
找到[一个](https://github.com/kevinaskin/apijson-node)
但是2年没有更新了，感觉协议有可能不一致

**Comment by TommyLemon** [comment]
这个应该是目前 Node 版中最完善的，不过和 Java 版差距还很大，确实在部分协议上不一致

**Comment by hezhongfeng** [comment]
好的，感谢回答。
