### ISSUE TITLE
DBVersion等是否可以通过配置去读取

### ISSUE THREAD

**Issue by hxdwd** [APIJSON/APIJSON-Demo#17]
从Demo工程上看，DemoSQLConfig下的其他数据库连接信息都可以放在yml文件里，除了DBVersion还有DEFAULT_SCHEMA，如果优雅的话，这些信息是否都可以配置化？感谢！

**Comment by TommyLemon** [comment]
应该都可以，按照 SpringBoot 的方式去配置下即可
