### ISSUE TITLE
不知大家试没有试APIJSONDemo-Druid和APIJSONDemo-HikariCP，这两个里面的application.yml并没有启效

### ISSUE THREAD

**Issue by ewsq** [APIJSON/APIJSON-Demo#23]
不知大家试没有试APIJSONDemo-Druid和APIJSONDemo-HikariCP，这两个里面的application.yml并没有启效。

不知怎么回事，我这里试必须在DemoSQLConfig.java中添加：
@JSONField(serialize = false)  // 不在日志打印 账号/密码 等敏感信息
@Override
public String getDBPassword() {
return "12345678";  // TODO 改成你自己的，TiDB 可以当成 MySQL 使用， 默认密码为空字符串 ""
}

这样的话就说明application.yml中的配置没有读取到或者启效。

如果试的时候可能大家直接使用了默认的用户和密码去建库和建用户，所以感觉上没有问题。

不知是不是这样。

**Comment by TommyLemon** [comment]
不应该出现这种情况，看下源码注释
https://github.com/APIJSON/APIJSON-Demo/blob/master/APIJSON-Java-Server/APIJSONDemo-Druid/src/main/java/apijson/demo/DemoSQLExecutor.java#L32-L34

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/5738175/178149635-e5e7386c-2e5e-4a3c-aea1-6f3c54a7bfd7.png">

**Comment by ewsq** [comment]
DemoSQLExecutor 在示例中断不住，并且显示也是灰色的，也就是这个类没有被任何地方调用。

**Comment by TommyLemon** [comment]
这两个连接池 Demo 漏了注册 SQLExecutor，仿照 SQLConfig 重写下方法
https://github.com/APIJSON/APIJSON-Demo/blob/master/APIJSON-Java-Server/APIJSONDemo-Druid/src/main/java/apijson/demo/DemoApplication.java#L66-L69
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/5738175/178936115-3c4448d9-56c0-4e3a-98f3-aaf78ad74930.png">

**Comment by TommyLemon** [comment]
应该是之前改了 APIJSONDemo 源码后同步给 APIJSONDemo-Druid 和 APIJSONDemo-HikariCP，不小心覆盖了 DemoApplication 中这段代码导致。

可以帮忙提交 PR(Pull Request) 贡献以上代码谢谢, 开源要大家一起参与贡献才会更美好~
<img width="943" alt="image" src="https://user-images.githubusercontent.com/5738175/178990178-0f15836c-d579-4c53-86bf-c61aedcac170.png">

https://github.com/Tencent/APIJSON/blob/master/CONTRIBUTING.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%80%E5%AE%9A%E8%A6%81%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81
