### ISSUE TITLE
在application.yml 中配置数据库连接信息？

### ISSUE THREAD

**Issue by loongjiang** [APIJSON/APIJSON-Demo#8]
数据库连接、用户名、密码 没法在application.yml 中配置？

**Comment by TommyLemon** [comment]
用连接池就可以

**Comment by loongjiang** [comment]
---------------------------------------------------------------------------------------------------------------------------------------
3)配置数据库(如果完成下方步骤 4，导入 APIJSON 的表，则可跳过)
打开 DemoSQLConfig 类，编辑 getDBUri，getDBAccount，getDBPassword，getSchema 的返回值为你自己数据库的配置。
---------------------------------------------------------------------------------------------------------------------------------------
文档只说了改代码返回自己的数据库配置，但没有说明怎么样把数据库连接信息配置到resource/application.yml中。。

**Comment by panmingjun** [comment]
注入DataSource，或者注入Environment然后自己去获取配置内容

**Comment by TommyLemon** [comment]
https://github.com/APIJSON/APIJSON-Demo/blob/master/APIJSON-Java-Server/APIJSONDemo-Druid/src/main/resources/application.yml
